<a href="https://colab.research.google.com/github/charlie-aashutosh/Machine-Learning/blob/master/marketing_analytics_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_excel("/content/a1_Dataset_10Percent.xlsx")

In [3]:
# shows count of rows and columns
dataset.shape

(22223, 11)

In [4]:
#shows first few rows of the code
dataset.head()

ID  DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg  \
0  17147654      5.0     NaN             NaN       NaN       NaN      NaN   
1   8415498     15.0     NaN             NaN         M       NaN      NaN   
2  12107603      NaN     NaN             NaN         M  Midlands     East   
3  14400995      8.0    28.0             NaN         F       NaN      NaN   
4  28724674     14.0    67.0             NaN       NaN       NaN      NaN   

  LoyalClass  LoyalSpend  LoyalTime  TargetBuy  
0        Tin        0.01        5.0          0  
1       Gold     8000.00        5.0          1  
2        Tin        0.01        NaN          1  
3        Tin        0.01        NaN          1  
4        Tin        0.01        7.0          0

In [5]:
#dropping customer ID column from the dataset
dataset=dataset.drop(['ID'],axis=1)
dataset.head()

DemAffl  DemAge DemClusterGroup DemGender    DemReg DemTVReg LoyalClass  \
0      5.0     NaN             NaN       NaN       NaN      NaN        Tin   
1     15.0     NaN             NaN         M       NaN      NaN       Gold   
2      NaN     NaN             NaN         M  Midlands     East        Tin   
3      8.0    28.0             NaN         F       NaN      NaN        Tin   
4     14.0    67.0             NaN       NaN       NaN      NaN        Tin   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01        5.0          0  
1     8000.00        5.0          1  
2        0.01        NaN          1  
3        0.01        NaN          1  
4        0.01        7.0          0

In [6]:
# explore missing values
dataset.isna().sum()

DemAffl            1085
DemAge             1508
DemClusterGroup     674
DemGender          2512
DemReg              465
DemTVReg            465
LoyalClass            0
LoyalSpend            0
LoyalTime           281
TargetBuy             0
dtype: int64

In [7]:
# filling missing values with mean for contineous data / mode for categorical data *

dataset['DemAffl']=dataset['DemAffl'].fillna(dataset['DemAffl'].mode()[0])
dataset['DemAge']=dataset['DemAge'].fillna(dataset['DemAge'].mode()[0])
dataset['DemClusterGroup']=dataset['DemClusterGroup'].fillna(dataset['DemClusterGroup'].mode()[0])
dataset['DemGender']=dataset['DemGender'].fillna(dataset['DemGender'].mode()[0])
dataset['DemReg']=dataset['DemReg'].fillna(dataset['DemReg'].mode()[0])
dataset['DemTVReg']=dataset['DemTVReg'].fillna(dataset['DemTVReg'].mode()[0])
dataset['LoyalTime']=dataset['LoyalTime'].fillna(dataset['LoyalTime'].mean())

In [8]:
dataset.isna().sum()

DemAffl            0
DemAge             0
DemClusterGroup    0
DemGender          0
DemReg             0
DemTVReg           0
LoyalClass         0
LoyalSpend         0
LoyalTime          0
TargetBuy          0
dtype: int64

In [9]:
dataset.head()

DemAffl  DemAge DemClusterGroup DemGender      DemReg DemTVReg LoyalClass  \
0      5.0    51.0               C         F  South East   London        Tin   
1     15.0    51.0               C         M  South East   London       Gold   
2      8.0    51.0               C         M    Midlands     East        Tin   
3      8.0    28.0               C         F  South East   London        Tin   
4     14.0    67.0               C         F  South East   London        Tin   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01    5.00000          0  
1     8000.00    5.00000          1  
2        0.01    6.56467          1  
3        0.01    6.56467          1  
4        0.01    7.00000          0

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22223 entries, 0 to 22222
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   DemAffl          22223 non-null  float64
 1   DemAge           22223 non-null  float64
 2   DemClusterGroup  22223 non-null  object 
 3   DemGender        22223 non-null  object 
 4   DemReg           22223 non-null  object 
 5   DemTVReg         22223 non-null  object 
 6   LoyalClass       22223 non-null  object 
 7   LoyalSpend       22223 non-null  float64
 8   LoyalTime        22223 non-null  float64
 9   TargetBuy        22223 non-null  int64  
dtypes: float64(4), int64(1), object(5)
memory usage: 1.7+ MB


In [14]:
dataset['DemClusterGroup'].unique()

array(['C', 'B', 'E', 'D', 'F', 'A', 'U'], dtype=object)

In [15]:
dataset['DemGender'].unique()

array(['F', 'M', 'U'], dtype=object)

In [16]:
dataset['DemReg'].unique()

array(['South East', 'Midlands', 'North', 'South West', 'Scottish'],
      dtype=object)

In [17]:
dataset['DemTVReg'].unique()

array(['London', 'East', 'Ulster', 'S & S East', 'Yorkshire',
       'Wales & West', 'N West', 'Midlands', 'S West', 'N East', 'N Scot',
       'C Scotland', 'Border'], dtype=object)

In [18]:
dataset['LoyalClass'].unique()

array(['Tin', 'Gold', 'Silver', 'Platinum'], dtype=object)

In [19]:
dataset['LoyalClass'].value_counts()

Silver      8572
Tin         6487
Gold        6324
Platinum     840
Name: LoyalClass, dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [21]:
dataset['DemClusterGroup']=label_encoder.fit_transform(dataset['DemClusterGroup'])

In [22]:
dataset['DemClusterGroup'].unique()

array([2, 1, 4, 3, 5, 0, 6])

In [23]:
dataset['DemGender']=label_encoder.fit_transform(dataset['DemGender'])

In [24]:
dataset['DemGender'].unique()

array([0, 1, 2])

In [25]:
dataset['DemReg']=label_encoder.fit_transform(dataset['DemReg'])

In [27]:
dataset['DemTVReg']=label_encoder.fit_transform(dataset['DemTVReg'])

In [28]:
dataset['LoyalClass']=label_encoder.fit_transform(dataset['LoyalClass'])

In [29]:
dataset.head()

DemAffl  DemAge  DemClusterGroup  DemGender  DemReg  DemTVReg  LoyalClass  \
0      5.0    51.0                2          0       3         3           3   
1     15.0    51.0                2          1       3         3           0   
2      8.0    51.0                2          1       0         2           3   
3      8.0    28.0                2          0       3         3           3   
4     14.0    67.0                2          0       3         3           3   

   LoyalSpend  LoyalTime  TargetBuy  
0        0.01    5.00000          0  
1     8000.00    5.00000          1  
2        0.01    6.56467          1  
3        0.01    6.56467          1  
4        0.01    7.00000          0

In [31]:
X=dataset.drop(['TargetBuy'],axis=1)
y=dataset['TargetBuy']

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [36]:
from sklearn.linear_model import LogisticRegression
classifier =  LogisticRegression(max_iter=200)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [37]:
# Exporting Logistic Regression Classifier to later use in prediction
import joblib
joblib.dump(classifier, './c2_Classifier_LoyalCustomers')

['./c2_Classifier_LoyalCustomers']

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
print(confusion_matrix(y_test,y_pred))

[[3193  174]
 [ 688  390]]


In [43]:
print(accuracy_score(y_test, y_pred))

0.80607424071991


In [44]:
predictions = classifier.predict_proba(X_test)
predictions

array([[0.86923426, 0.13076574],
       [0.64629791, 0.35370209],
       [0.44173656, 0.55826344],
       ...,
       [0.87835124, 0.12164876],
       [0.90873153, 0.09126847],
       [0.88944614, 0.11055386]])